oci_client:
  configProfile: "DEFAULT"
  compartiment:  ${COMPARTIMENT}
  endpoint:  ${ENDPOINT}
  config_path:  ${CONFIG_PATH}

credentials:
  DIDACTIC_USER: ${DIDACTIC_USER}
  DIDACTIC_PASSWORD: ${DIDACTIC_PASSWORD}